# Generated by Django 5.2.7 on 2026-03-20 08:49

import netfields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPLocation',
            fields=[
                ('network', netfields.fields.CidrAddressField(max_length=43, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100, null=True)),
                ('region', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=2, null=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['network'], name='idx_ip_network_gist', opclasses=['inet_ops'])],
            },
        ),
    ]
