import type { Tutor, Parent, Booking, Rating, Like, ProgressEntry } from "./types";

export const TUTORS: Tutor[] = [
  {
    id: "t1",
    full_name: "Kofi Asante",
    location: "East Legon",
    subjects: ["Mathematics", "Integrated Science"],
    experience_years: 8,
    hourly_rate: 80,
    average_rating: 4.9,
    total_sessions: 142,
    total_likes: 38,
    response_time_hours: 1,
    completion_rate: 98,
    verified: true,
    qualifications: "B.Ed Mathematics, University of Ghana",
    bio: "Passionate mathematics educator with over 8 years of experience teaching JHS students across Greater Accra.",
  },
  {
    id: "t2",
    full_name: "Abena Mensah",
    location: "Osu",
    subjects: ["ICT/Computing", "Mathematics"],
    experience_years: 5,
    hourly_rate: 65,
    average_rating: 4.7,
    total_sessions: 89,
    total_likes: 24,
    response_time_hours: 2,
    completion_rate: 95,
    verified: true,
    qualifications: "BSc Computer Science, KNUST",
    bio: "ICT specialist focused on making coding accessible and fun for young learners.",
  },
  {
    id: "t3",
    full_name: "Emmanuel Boateng",
    location: "Tema",
    subjects: ["Basic Design & Technology", "Mathematics"],
    experience_years: 6,
    hourly_rate: 55,
    average_rating: 4.6,
    total_sessions: 76,
    total_likes: 19,
    response_time_hours: 3,
    completion_rate: 92,
    verified: false,
    qualifications: "Diploma in Technical Education, Cape Coast",
    bio: "Technical education tutor with hands-on experience in design and technology.",
  },
  {
    id: "t4",
    full_name: "Ama Darko",
    location: "Adenta",
    subjects: ["Integrated Science", "Mathematics"],
    experience_years: 4,
    hourly_rate: 50,
    average_rating: 4.8,
    total_sessions: 65,
    total_likes: 31,
    response_time_hours: 1,
    completion_rate: 97,
    verified: true,
    qualifications: "BSc Biological Sciences, University of Ghana",
    bio: "Science tutor passionate about helping students discover the wonders of nature and scientific inquiry.",
  },
  {
    id: "t5",
    full_name: "Kweku Frimpong",
    location: "Spintex",
    subjects: ["Mathematics", "ICT/Computing"],
    experience_years: 10,
    hourly_rate: 100,
    average_rating: 5.0,
    total_sessions: 203,
    total_likes: 57,
    response_time_hours: 1,
    completion_rate: 99,
    verified: true,
    qualifications: "MSc Applied Mathematics, KNUST",
    bio: "Senior mathematics and computing tutor with a decade of excellence in STEM education.",
  },
  {
    id: "t6",
    full_name: "Efua Boakye",
    location: "Madina",
    subjects: ["Integrated Science", "Basic Design & Technology"],
    experience_years: 3,
    hourly_rate: 45,
    average_rating: 4.5,
    total_sessions: 41,
    total_likes: 12,
    response_time_hours: 4,
    completion_rate: 90,
    verified: false,
    qualifications: "Diploma in General Science Education",
    bio: "Energetic young tutor bringing fresh teaching methods to science and technology education.",
  },
  {
    id: "t7",
    full_name: "Nana Brew",
    location: "Dansoman",
    subjects: ["Mathematics"],
    experience_years: 7,
    hourly_rate: 70,
    average_rating: 4.7,
    total_sessions: 118,
    total_likes: 29,
    response_time_hours: 2,
    completion_rate: 96,
    verified: true,
    qualifications: "B.Ed Mathematics, UESD",
    bio: "Dedicated mathematics tutor with proven track record of improving student exam scores.",
  },
  {
    id: "t8",
    full_name: "Akosua Tetteh",
    location: "Kaneshie",
    subjects: ["ICT/Computing"],
    experience_years: 2,
    hourly_rate: 40,
    average_rating: 4.4,
    total_sessions: 28,
    total_likes: 8,
    response_time_hours: 5,
    completion_rate: 88,
    verified: false,
    qualifications: "HND Information Technology, Accra Polytechnic",
    bio: "Young ICT enthusiast helping students navigate the digital world with confidence.",
  },
];

export const PARENTS: Parent[] = [
  {
    id: "p1",
    full_name: "Adjoa Mensah",
    email: "parent@demo.com",
    location: "East Legon",
    subjects_needed: ["Mathematics", "Integrated Science"],
    child_grade: "JHS 2",
    total_bookings: 5,
    role: "parent",
  },
  {
    id: "p2",
    full_name: "Kwame Boateng",
    email: "kwame@demo.com",
    location: "Cantonments",
    subjects_needed: ["Mathematics", "Integrated Science"],
    child_grade: "JHS 3",
    total_bookings: 2,
    role: "parent",
  },
];

export const BOOKINGS: Booking[] = [
  {
    id: "b1",
    parent_id: "p1",
    tutor_id: "t1",
    subjects: ["Mathematics"],
    session_date: Date.now() + 86400000 * 3,
    duration_hours: 2,
    status: "Confirmed",
    location: "East Legon",
    total_cost: 160,
  },
  {
    id: "b2",
    parent_id: "p1",
    tutor_id: "t4",
    subjects: ["Integrated Science"],
    session_date: Date.now() + 86400000 * 7,
    duration_hours: 1.5,
    status: "Pending",
    location: "Adenta",
    total_cost: 75,
  },
  {
    id: "b3",
    parent_id: "p1",
    tutor_id: "t1",
    subjects: ["Mathematics"],
    session_date: Date.now() - 86400000 * 10,
    duration_hours: 2,
    status: "Completed",
    location: "East Legon",
    total_cost: 160,
  },
  {
    id: "b4",
    parent_id: "p2",
    tutor_id: "t1",
    subjects: ["Mathematics", "Integrated Science"],
    session_date: Date.now() + 86400000 * 2,
    duration_hours: 1.5,
    status: "Pending",
    location: "Cantonments",
    notes: "My son is struggling with algebra and basic chemistry.",
    total_cost: 120,
  },
  {
    id: "b5",
    parent_id: "p1",
    tutor_id: "t1",
    subjects: ["Mathematics"],
    session_date: Date.now() + 86400000 * 5,
    duration_hours: 1,
    status: "Pending",
    location: "East Legon",
    notes: "Revision for upcoming exams.",
    total_cost: 80,
  },
];

export const RATINGS: Rating[] = [
  {
    id: "r1",
    tutor_id: "t1",
    parent_id: "p1",
    rating_score: 5,
    review_text:
      "Mr. Asante is an exceptional tutor! My daughter's math grades improved dramatically.",
    review_date: Date.now() - 86400000 * 5,
  },
  {
    id: "r2",
    tutor_id: "t1",
    parent_id: "p2",
    rating_score: 4.8,
    review_text: "Very patient and knowledgeable. Highly recommend for JHS students.",
    review_date: Date.now() - 86400000 * 15,
  },
  {
    id: "r3",
    tutor_id: "t4",
    parent_id: "p1",
    rating_score: 4.9,
    review_text: "Ama is wonderful with kids. My son loves his science sessions.",
    review_date: Date.now() - 86400000 * 20,
  },
];

export const LIKES: Like[] = [
  { id: "l1", tutor_id: "t1", parent_id: "p1", liked: true },
  { id: "l2", tutor_id: "t4", parent_id: "p1", liked: true },
];

export const PROGRESS: ProgressEntry[] = [
  {
    id: "pr1",
    tutor_id: "t1",
    parent_id: "p1",
    subject: "Mathematics",
    date: Date.now() - 86400000 * 10,
    topic: "Algebra — Linear Equations",
    performance: "Good",
    notes: "Solved 8/10 problems correctly. Struggles with negative integers.",
  },
  {
    id: "pr2",
    tutor_id: "t1",
    parent_id: "p1",
    subject: "Mathematics",
    date: Date.now() - 86400000 * 5,
    topic: "Algebra — Quadratic Equations",
    performance: "Needs Work",
    notes: "Introduced quadratics. Needs more practice with factoring.",
  },
  {
    id: "pr3",
    tutor_id: "t1",
    parent_id: "p2",
    subject: "Integrated Science",
    date: Date.now() - 86400000 * 7,
    topic: "Photosynthesis",
    performance: "Excellent",
    notes: "Excellent recall. Drew accurate diagrams and explained the process clearly.",
  },
];