# Generated by Django 5.2.7 on 2026-02-19 15:30

import django.db.models.deletion
import user_auth.utils.model_fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent_Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.TextField(null=True)),
                ('email', models.TextField(null=True)),
                ('phone_number', models.TextField(null=True)),
                ('location', models.TextField(null=True)),
                ('id_number', models.TextField(null=True)),
                ('id_type', models.TextField(choices=[('Passport', 'passport'), ('Driver License', 'driver_license'), ('National ID', 'national_id'), ('Voter ID', 'voter_id')], null=True)),
                ('id_verified', models.BooleanField(default=False)),
                ('number_of_children', models.IntegerField(null=True)),
                ('child_grade', models.TextField(null=True)),
                ('subjects_needed', models.TextField(null=True)),
                ('profile_picture_key', models.TextField(null=True)),
                ('verified', models.BooleanField(default=False)),
                ('favorite_tutors', models.TextField(null=True)),
                ('total_bookings', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preferences', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_hash', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(user_auth.utils.model_fields.CryptoMixin, models.Model),
        ),
    ]
