# Generated by Django 5.2.7 on 2026-03-31 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent_profile',
            name='email_hash',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
