# Generated by Django 5.2.7 on 2026-03-31 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0002_alter_parent_profile_email_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent_profile',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
