# Generated by Django 5.2.7 on 2026-02-19 15:28

import user_auth.utils.model_fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor_Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.TextField()),
                ('email', models.TextField()),
                ('email_hash', models.TextField(null=True)),
                ('phone_number', models.TextField()),
                ('age', models.TextField()),
                ('id_number', models.TextField()),
                ('id_type', models.TextField(choices=[('Passport', 'passport'), ('Driver License', 'driver_license'), ('National ID', 'national_id'), ('Voter ID', 'voter_id'), ('certificate', 'Certificate')])),
                ('id_verified', models.BooleanField(default=False)),
                ('experience_years', models.IntegerField()),
                ('qualifications', models.TextField()),
                ('location', models.TextField()),
                ('subjects_slug', models.CharField(blank=True, db_index=True, editable=False, max_length=500, null=True)),
                ('location_slug', models.CharField(blank=True, db_index=True, editable=False, max_length=200, null=True)),
                ('profile_picture_key', models.TextField()),
                ('verified', models.BooleanField(default=False)),
                ('total_sessions', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('total_likes', models.IntegerField(default=0)),
                ('response_time_hours', models.IntegerField()),
                ('completion_rate', models.FloatField(default=0.0)),
                ('status', models.TextField(choices=[('Active', 'active'), ('Inactive', 'inactive'), ('Suspended', 'suspended')])),
                ('subjects', models.TextField()),
                ('bio', models.TextField(null=True)),
                ('availability', models.TextField()),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            bases=(user_auth.utils.model_fields.CryptoMixin, models.Model),
        ),
    ]
