# Generated by Django 5.2.7 on 2026-03-31 19:31

import django.core.validators
import django.db.models.deletion
import user_auth.utils.model_fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0003_rename_profile_picture_key_tutor_profile_profile_picture_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tutor_profile',
            name='id_type',
            field=models.TextField(choices=[('Passport', 'passport'), ('Driver License', 'driver_license'), ('National ID', 'national_id'), ('Voter ID', 'voter_id'), ('Certificate', 'Certificate')]),
        ),
        migrations.AlterField(
            model_name='tutor_profile',
            name='subjects_slug',
            field=models.SlugField(blank=True, editable=False, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tutorrating',
            name='score',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tutors.tutor_profile')),
                ('subjects', models.ManyToManyField(null=True, related_name='bookings', to='tutors.subject')),
            ],
            bases=(user_auth.utils.model_fields.CryptoMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TutorEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earning_record', to='tutors.booking')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings_records', to='tutors.tutor_profile')),
            ],
        ),
    ]
